import { WebClient } from '@slack/web-api';
import { AnalyzedNotification } from '../types.js';
import * as core from '@actions/core';

export class DMService {
  private slackClient?: WebClient;
  private slackUserId?: string;

  constructor(slackToken?: string, slackUserId?: string) {
    if (slackToken && slackUserId) {
      this.slackClient = new WebClient(slackToken);
      this.slackUserId = slackUserId;
    }
  }

  async sendActionItemsDM(
    username: string,
    notifications: AnalyzedNotification[]
  ): Promise<void> {
    const message = this.formatActionItems(notifications);
    
    // Try to send via Slack if configured
    if (this.slackClient && this.slackUserId) {
      try {
        await this.sendSlackDM(notifications);
        core.info('✅ Sent Slack DM successfully!');
      } catch (error) {
        core.warning(`Failed to send Slack DM: ${error}`);
        core.warning('Falling back to console output...');
        this.logToConsole(message);
      }
    } else {
      core.info('No Slack credentials provided. Outputting to console...');
      this.logToConsole(message);
    }
  }

  private async sendSlackDM(notifications: AnalyzedNotification[]): Promise<void> {
    if (!this.slackClient || !this.slackUserId) {
      throw new Error('Slack client not initialized');
    }

    const blocks = this.formatSlackBlocks(notifications);
    
    await this.slackClient.chat.postMessage({
      channel: this.slackUserId,
      text: `You have ${notifications.length} important notification(s) requiring attention`,
      blocks,
    });
  }

  private logToConsole(message: string): void {
    console.log('\n' + '='.repeat(80));
    console.log('ACTION ITEMS - IMPORTANT NOTIFICATIONS');
    console.log('='.repeat(80) + '\n');
    console.log(message);
    console.log('\n' + '='.repeat(80) + '\n');
  }

  private formatSlackBlocks(notifications: AnalyzedNotification[]): any[] {
    const blocks: any[] = [
      {
        type: 'header',
        text: {
          type: 'plain_text',
          text: '🔔 Important GitHub Notifications',
          emoji: true,
        },
      },
      {
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: `You have *${notifications.length}* important notification(s) requiring your attention:`,
        },
      },
      {
        type: 'divider',
      },
    ];

    // Sort by importance and limit to top 20 to stay under Slack's 50 block limit
    // Each notification uses ~2 blocks (section + divider), plus ~5 blocks for header/footer
    const maxNotifications = 20;
    const sorted = notifications.sort((a, b) => b.importance - a.importance);
    const displayed = sorted.slice(0, maxNotifications);
    const remaining = sorted.length - displayed.length;

    displayed.forEach((notif, index) => {
      const importanceEmoji = '⭐'.repeat(notif.importance);
      
      blocks.push({
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: `*${index + 1}. ${notif.repository.full_name}*\n${importanceEmoji} Importance: ${notif.importance}/5\n\n*${notif.subject.title}*\n\n📝 ${notif.summary}\n✅ *Action:* ${notif.actionRequired}`,
        },
        accessory: {
          type: 'button',
          text: {
            type: 'plain_text',
            text: 'View',
            emoji: true,
          },
          url: notif.subject.url || notif.repository.html_url,
          action_id: `view_${notif.id}`,
        },
      });

      if (index < displayed.length - 1) {
        blocks.push({ type: 'divider' });
      }
    });

    // Add note if there are more notifications
    if (remaining > 0) {
      blocks.push(
        { type: 'divider' },
        {
          type: 'section',
          text: {
            type: 'mrkdwn',
            text: `_... and ${remaining} more notification(s). Check GitHub for the full list._`,
          },
        }
      );
    }

    // Add footer
    blocks.push(
      {
        type: 'divider',
      },
      {
        type: 'context',
        elements: [
          {
            type: 'mrkdwn',
            text: `Generated by Notification Helper • ${new Date().toLocaleString()}`,
          },
        ],
      }
    );

    return blocks;
  }

  private formatActionItems(notifications: AnalyzedNotification[]): string {
    let message = `You have ${notifications.length} important notification(s) requiring your attention:\n\n`;

    notifications
      .sort((a, b) => b.importance - a.importance)
      .forEach((notif, index) => {
        message += `${index + 1}. **[${notif.repository.full_name}]** ${notif.subject.title}\n`;
        message += `   📍 Importance: ${notif.importance}/5\n`;
        message += `   📝 Summary: ${notif.summary}\n`;
        message += `   ✅ Action Required: ${notif.actionRequired}\n`;
        message += `   🔗 Link: ${notif.subject.url || notif.repository.html_url}\n`;
        message += `   ⏰ Updated: ${new Date(notif.updated_at).toLocaleString()}\n\n`;
      });

    return message;
  }
}
